repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9  # should match ruff version in this repo
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: commitlint --edit
        language: node
        stages: [commit-msg]
        additional_dependencies:
          - '@commitlint/cli@17.8.1'
          - '@commitlint/config-conventional@17.8.1'
