[project]
name = "aai-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "python-jose>=3.4.0",
    "requests>=2.32.3",
]

[tool.pytest.ini_options]
pythonpath=["."]
testpaths=["tests"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
