"""user_query_indexes

Revision ID: 038392d88518
Revises: 59775ffa2413
Create Date: 2026-04-02 16:32:18.599767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '038392d88518'
down_revision: Union[str, None] = '59775ffa2413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_biocommons_user_email_verified_deleted', 'biocommons_user', ['email_verified', 'is_deleted'], unique=False)
    op.create_index('ix_groupmembership_user_group_deleted', 'groupmembership', ['user_id', 'group_id', 'is_deleted'], unique=False)
    op.create_index('ix_platformmembership_user_platform_deleted', 'platformmembership', ['user_id', 'platform_id', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_platformmembership_user_platform_deleted', table_name='platformmembership')
    op.drop_index('ix_groupmembership_user_group_deleted', table_name='groupmembership')
    op.drop_index('ix_biocommons_user_email_verified_deleted', table_name='biocommons_user')
    # ### end Alembic commands ###
