"""unlink_sbp_service_admin_from_bundle

Revision ID: 0d2a0acf71bb
Revises: 37a648289324
Create Date: 2026-07-06 14:17:16.280278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d2a0acf71bb'
down_revision: Union[str, None] = '37a648289324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
