"""add_request_reason_to_memberships

Revision ID: 0d2dd5140f8a
Revises: f240539a962b
Create Date: 2026-02-16 15:52:42.138727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d2dd5140f8a'
down_revision: Union[str, None] = 'f240539a962b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupmembership', sa.Column('request_reason', sa.String(length=255), nullable=True))
    op.add_column('platformmembership', sa.Column('request_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platformmembership', 'request_reason')
    op.drop_column('groupmembership', 'request_reason')
    # ### end Alembic commands ###
