"""user_email_verified

Revision ID: 1546c07b9d78
Revises: a8cb5fd2d258
Create Date: 2025-09-15 11:37:09.829832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1546c07b9d78'
down_revision: Union[str, None] = 'a8cb5fd2d258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biocommons_user', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biocommons_user', 'email_verified')
    # ### end Alembic commands ###
