"""add_requested_at_to_group_membership

Revision ID: 274454823044
Revises: 98e639b5731f
Create Date: 2026-05-12 10:38:57.530656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '274454823044'
down_revision: Union[str, None] = '98e639b5731f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupmembership', sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groupmembership', 'requested_at')
    # ### end Alembic commands ###
