"""add_short_name_to_biocommons_group

Revision ID: 30fd168b9c90
Revises: ff6e32a9c164
Create Date: 2025-10-14 11:23:53.350674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '30fd168b9c90'
down_revision: Union[str, None] = 'ff6e32a9c164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {column["name"] for column in inspector.get_columns("biocommonsgroup")}

    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first (only when missing)
    if "short_name" not in columns:
        op.add_column('biocommonsgroup', sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Populate existing rows with short names
    connection = bind
    connection.execute(
        sa.text("""
            UPDATE biocommonsgroup
            SET short_name = CASE
                WHEN group_id = 'biocommons/group/tsi' THEN 'TSI'
                WHEN group_id = 'biocommons/group/bpa_galaxy' THEN 'BPA-GA'
                ELSE group_id
            END
            WHERE short_name IS NULL
        """)
    )

    # Make the column non-nullable and add the unique constraint via batch mode on sqlite
    bind = op.get_bind()
    dialect_name = bind.dialect.name

    if dialect_name == "sqlite":
        with op.batch_alter_table("biocommonsgroup") as batch_op:
            batch_op.alter_column("short_name", nullable=False)
            batch_op.create_unique_constraint(op.f("uq_biocommonsgroup_short_name"), ["short_name"])
    else:
        op.alter_column('biocommonsgroup', 'short_name', nullable=False)
        op.create_unique_constraint(op.f('uq_biocommonsgroup_short_name'), 'biocommonsgroup', ['short_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_biocommonsgroup_short_name'), 'biocommonsgroup', type_='unique')
    op.drop_column('biocommonsgroup', 'short_name')
    # ### end Alembic commands ###
