"""add_short_name_to_biocommons_group

Revision ID: 30fd168b9c90
Revises: ff6e32a9c164
Create Date: 2025-10-14 11:23:53.350674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '30fd168b9c90'
down_revision: Union[str, None] = 'ff6e32a9c164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biocommonsgroup', sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(op.f('uq_biocommonsgroup_short_name'), 'biocommonsgroup', ['short_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_biocommonsgroup_short_name'), 'biocommonsgroup', type_='unique')
    op.drop_column('biocommonsgroup', 'short_name')
    # ### end Alembic commands ###
