"""platform_role_name

Revision ID: 4271e34a0adf
Revises: 6c9d1e8540be
Create Date: 2025-11-04 11:41:03.519358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4271e34a0adf'
down_revision: Union[str, None] = '6c9d1e8540be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_auth0role_name'), 'auth0role', ['name'])
    op.add_column('platform', sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(op.f('fk_platform_role_name_auth0role'), 'platform', 'auth0role', ['role_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_platform_role_name_auth0role'), 'platform', type_='foreignkey')
    op.drop_column('platform', 'role_name')
    op.drop_constraint(op.f('uq_auth0role_name'), 'auth0role', type_='unique')
    # ### end Alembic commands ###
