"""user_history

Revision ID: 44d8dc065b59
Revises: f240539a962b
Create Date: 2026-02-09 13:46:53.503672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44d8dc065b59'
down_revision: Union[str, None] = 'f240539a962b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biocommonsuserhistory',
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('change', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['biocommons_user.id'], name=op.f('fk_biocommonsuserhistory_updated_by_id_biocommons_user')),
    sa.ForeignKeyConstraint(['user_id'], ['biocommons_user.id'], name=op.f('fk_biocommonsuserhistory_user_id_biocommons_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biocommonsuserhistory'))
    )
    op.create_index(op.f('ix_biocommonsuserhistory_is_deleted'), 'biocommonsuserhistory', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biocommonsuserhistory_is_deleted'), table_name='biocommonsuserhistory')
    op.drop_table('biocommonsuserhistory')
    # ### end Alembic commands ###
