"""platform_roles

Revision ID: 4594b458279c
Revises: 6c9d1e8540be
Create Date: 2025-11-05 14:05:57.399804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4594b458279c'
down_revision: Union[str, None] = '6c9d1e8540be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    platform_columns = {column["name"] for column in inspector.get_columns("platform")}
    if "role_id" not in platform_columns:
        op.add_column('platform', sa.Column('role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    dialect_name = bind.dialect.name
    fk_name = op.f('fk_platform_role_id_auth0role')
    if dialect_name == "sqlite":
        with op.batch_alter_table("platform", recreate="always") as batch_op:
            batch_op.create_foreign_key(fk_name, "auth0role", ["role_id"], ["id"], ondelete="SET NULL")
    else:
        op.create_foreign_key(fk_name, 'platform', 'auth0role', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    fk_name = op.f('fk_platform_role_id_auth0role')
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if bind.dialect.name == "sqlite":
        with op.batch_alter_table("platform", recreate="always") as batch_op:
            batch_op.drop_constraint(fk_name, type_='foreignkey')
    else:
        op.drop_constraint(fk_name, 'platform', type_='foreignkey')
    op.drop_column('platform', 'role_id')
    # ### end Alembic commands ###
