"""other_user_id

Revision ID: 98fbefd9f191
Revises: 0c91366532ae
Create Date: 2026-08-24 15:43:31.428645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98fbefd9f191'
down_revision: Union[str, None] = '0c91366532ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biocommons_user', sa.Column('other_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biocommons_user', 'other_user_id')
    # ### end Alembic commands ###
