"""add_edna_explorer_platform

Revision ID: b7a0db5cbcc0
Revises: 4000ecb2796d
Create Date: 2026-07-28 13:45:47.641039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'b7a0db5cbcc0'
down_revision: Union[str, None] = '4000ecb2796d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='PlatformEnum',
        new_values=['GALAXY', 'BPA_DATA_PORTAL', 'SBP', 'EDNA_EXPLORER'],
        affected_columns=[TableReference(table_schema='public', table_name='platform', column_name='id'), TableReference(table_schema='public', table_name='platformmembership', column_name='platform_id'), TableReference(table_schema='public', table_name='platformmembershiphistory', column_name='platform_id'), TableReference(table_schema='public', table_name='platformrolelink', column_name='platform_id')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='PlatformEnum',
        new_values=['GALAXY', 'BPA_DATA_PORTAL', 'SBP'],
        affected_columns=[TableReference(table_schema='public', table_name='platform', column_name='id'), TableReference(table_schema='public', table_name='platformmembership', column_name='platform_id'), TableReference(table_schema='public', table_name='platformmembershiphistory', column_name='platform_id'), TableReference(table_schema='public', table_name='platformrolelink', column_name='platform_id')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
