"""add-sender-email-in-emailnotification

Revision ID: c563e06b01b3
Revises: d6a5578732bc
Create Date: 2025-11-26 11:16:37.783670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c563e06b01b3'
down_revision: Union[str, None] = 'd6a5578732bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailnotification', sa.Column('from_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_emailnotification_from_address'), 'emailnotification', ['from_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emailnotification_from_address'), table_name='emailnotification')
    op.drop_column('emailnotification', 'from_address')
    # ### end Alembic commands ###
