"""add-sender-email-in-emailnotification

Revision ID: c563e06b01b3
Revises: d6a5578732bc
Create Date: 2025-11-26 11:16:37.783670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c563e06b01b3'
down_revision: Union[str, None] = 'd6a5578732bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    dialect = bind.dialect.name

    if dialect == "sqlite":
        # SQLite cannot run ALTER COLUMN; add the column with NOT NULL + default directly.
        op.add_column(
            "emailnotification",
            sa.Column(
                "from_address",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="",
            ),
        )
    else:
        op.add_column(
            "emailnotification",
            sa.Column(
                "from_address",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
                server_default="",
            ),
        )
        op.execute(sa.text("UPDATE emailnotification SET from_address = '' WHERE from_address IS NULL"))
        op.alter_column(
            "emailnotification",
            "from_address",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default=None,
        )

    op.create_index(op.f('ix_emailnotification_from_address'), 'emailnotification', ['from_address'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emailnotification_from_address'), table_name='emailnotification')
    op.drop_column('emailnotification', 'from_address')
    # ### end Alembic commands ###
