"""make_datetime_columns_timezone_aware

Revision ID: c5ec222dd539
Revises: c4c7a8e9b2d3
Create Date: 2025-12-05 14:57:09.838400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5ec222dd539'
down_revision: Union[str, None] = 'c4c7a8e9b2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only apply timestamp changes for PostgreSQL (SQLite doesn't support ALTER COLUMN TYPE)
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        # Convert existing naive timestamps to timezone-aware, treating them as UTC
        op.execute("ALTER TABLE biocommons_user ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'")
        op.execute("ALTER TABLE groupmembership ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC'")
        op.execute("ALTER TABLE groupmembershiphistory ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC'")
        op.execute("ALTER TABLE platformmembership ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC'")
        op.execute("ALTER TABLE platformmembershiphistory ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC'")

        # EmailNotification table datetime columns
        op.execute("ALTER TABLE emailnotification ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'")
        op.execute("ALTER TABLE emailnotification ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC'")
        op.execute("ALTER TABLE emailnotification ALTER COLUMN send_after TYPE TIMESTAMP WITH TIME ZONE USING send_after AT TIME ZONE 'UTC'")
        op.execute("ALTER TABLE emailnotification ALTER COLUMN sent_at TYPE TIMESTAMP WITH TIME ZONE USING sent_at AT TIME ZONE 'UTC'")
        op.execute("ALTER TABLE emailnotification ALTER COLUMN last_attempt_at TYPE TIMESTAMP WITH TIME ZONE USING last_attempt_at AT TIME ZONE 'UTC'")

        # EmailChangeOtp table datetime columns
        op.execute("ALTER TABLE email_change_otps ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'")
        op.execute("ALTER TABLE email_change_otps ALTER COLUMN expires_at TYPE TIMESTAMP WITH TIME ZONE USING expires_at AT TIME ZONE 'UTC'")
    # For SQLite, no schema changes needed - timezone handling is done at the application layer
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only apply timestamp changes for PostgreSQL (SQLite doesn't support ALTER COLUMN TYPE)
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        # Revert timezone-aware timestamps back to naive timestamps
        op.alter_column('email_change_otps', 'expires_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=False)
        op.alter_column('email_change_otps', 'created_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=False)
        op.alter_column('emailnotification', 'last_attempt_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=True)
        op.alter_column('emailnotification', 'sent_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=True)
        op.alter_column('emailnotification', 'send_after',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=True)
        op.alter_column('emailnotification', 'updated_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=False)
        op.alter_column('emailnotification', 'created_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=False)
        op.alter_column('platformmembershiphistory', 'updated_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=False)
        op.alter_column('platformmembership', 'updated_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=False)
        op.alter_column('groupmembershiphistory', 'updated_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=False)
        op.alter_column('groupmembership', 'updated_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=False)
        op.alter_column('biocommons_user', 'created_at',
                   existing_type=sa.DateTime(timezone=True),
                   type_=postgresql.TIMESTAMP(),
                   existing_nullable=False)
    # For SQLite, no schema changes needed
    # ### end Alembic commands ###
