"""email-scheduler-update

Revision ID: cb3235fee78d
Revises: 9f2d8c1b5d4e
Create Date: 2025-11-24 14:20:21.025725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb3235fee78d'
down_revision: Union[str, None] = '9f2d8c1b5d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailnotification', sa.Column('first_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emailnotification', 'first_attempt_at')
    # ### end Alembic commands ###
