"""new-email-queue

Revision ID: d64e9ebd0253
Revises: 4594b458279c
Create Date: 2025-11-20 14:30:18.888335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd64e9ebd0253'
down_revision: Union[str, None] = '4594b458279c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailnotification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('to_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENDING', 'SENT', 'FAILED', name='EmailStatusEnum'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('send_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emailnotification'))
    )
    op.create_index(op.f('ix_emailnotification_status'), 'emailnotification', ['status'], unique=False)
    op.create_index(op.f('ix_emailnotification_to_address'), 'emailnotification', ['to_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emailnotification_to_address'), table_name='emailnotification')
    op.drop_index(op.f('ix_emailnotification_status'), table_name='emailnotification')
    op.drop_table('emailnotification')
    # ### end Alembic commands ###
