"""user_deletion_fields

Revision ID: f240539a962b
Revises: c5ec222dd539
Create Date: 2026-01-07 15:07:54.566160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f240539a962b'
down_revision: Union[str, None] = 'c5ec222dd539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biocommons_user', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('biocommons_user', sa.Column('deletion_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biocommons_user', 'deletion_reason')
    op.drop_column('biocommons_user', 'deleted_at')
    # ### end Alembic commands ###
