"""user_deletion_fields

Revision ID: f240539a962b
Revises: c5ec222dd539
Create Date: 2026-01-07 15:07:54.566160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f240539a962b'
down_revision: Union[str, None] = 'c5ec222dd539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biocommons_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deletion_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key(
            op.f('fk_biocommons_user_deleted_by_id_biocommons_user'),
            'biocommons_user',
            ['deleted_by_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biocommons_user', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('fk_biocommons_user_deleted_by_id_biocommons_user'), type_='foreignkey')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deletion_reason')
        batch_op.drop_column('deleted_at')
    # ### end Alembic commands ###
