"""revoke_reason

Revision ID: ff6e32a9c164
Revises: 08a3d0593418
Create Date: 2025-09-30 08:44:03.291337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff6e32a9c164'
down_revision: Union[str, None] = '08a3d0593418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupmembership', sa.Column('revocation_reason', sa.String(length=1024), nullable=True))
    op.add_column('groupmembershiphistory', sa.Column('reason', sa.String(length=1024), nullable=True))
    op.add_column('platformmembership', sa.Column('revocation_reason', sa.String(length=1024), nullable=True))
    op.add_column('platformmembershiphistory', sa.Column('reason', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platformmembershiphistory', 'reason')
    op.drop_column('platformmembership', 'revocation_reason')
    op.drop_column('groupmembershiphistory', 'reason')
    op.drop_column('groupmembership', 'revocation_reason')
    # ### end Alembic commands ###
