name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::232870232581:role/aai-backend-deploy
          role-session-name: github-test-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          uv sync --extra dev

      - name: Run Ruff (lint)
        run: |
          uv run -- ruff check .

      - name: Run tests and generate Cobertura coverage report
        env:
          AUTH0_DOMAIN: "mock-domain"
          AUTH0_AUDIENCE: "mock-audience"
          AUTH0_MANAGEMENT_ID: "mock-id"
          AUTH0_MANAGEMENT_SECRET: "mock-secret"
          AWS_REGION: ap-southeast-2
        run: |
          mkdir -p coverage
          PYTHONPATH=. uv run pytest \
            --cov \
            --cov-report=term-missing \
            --cov-report=xml:coverage/cobertura.xml \
            --cov-fail-under=80 \
            --cov-report=html:coverage/html

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: true
          hide_complexity: true
          indicators: true
          output: console
          thresholds: '80 80'
