name: Run Pytest with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      AUTH0_DOMAIN: "mock-domain"
      AUTH0_AUDIENCE: "mock-audience"
      AUTH0_MANAGEMENT_ID: "mock-id"
      AUTH0_MANAGEMENT_SECRET: "mock-secret"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          uv sync --dev  # Include dev tools like pytest and pytest-cov

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=aai_backend --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Optional for public repos
          files: ./coverage.xml
          fail_ci_if_error: true
